OPTEE_RUST_EXAMPLES_EXT_VERSION = 1.0
OPTEE_RUST_EXAMPLES_EXT_SOURCE = local
OPTEE_RUST_EXAMPLES_EXT_SITE = $(BR2_PACKAGE_OPTEE_RUST_EXAMPLES_EXT_SITE)
OPTEE_RUST_EXAMPLES_EXT_SITE_METHOD = local
OPTEE_RUST_EXAMPLES_EXT_INSTALL_STAGING = YES
OPTEE_RUST_EXAMPLES_EXT_DEPENDENCIES = optee_client_ext host-jq
OPTEE_RUST_EXAMPLES_EXT_SDK = $(BR2_PACKAGE_OPTEE_RUST_EXAMPLES_EXT_SDK)
OPTEE_RUST_EXAMPLES_EXT_RUST_TC_PATH = $(subst $\",,$(BR2_PACKAGE_OPTEE_RUST_EXAMPLES_EXT_TC_PATH))
OPTEE_RUST_EXAMPLES_EXT_TA_TC_BIN_PATH = $(dir $(BR2_PACKAGE_OPTEE_RUST_EXAMPLES_EXT_CROSS_COMPILE_TA))
OPTEE_RUST_EXAMPLES_EXT_HOST_TC_BIN_PATH = $(dir $(BR2_PACKAGE_OPTEE_RUST_EXAMPLES_EXT_CROSS_COMPILE_HOST))
OPTEE_RUST_EXAMPLES_EXT_TA_ARCH = $(if $(findstring aarch64,$(BR2_PACKAGE_OPTEE_RUST_EXAMPLES_EXT_CROSS_COMPILE_TA)),aarch64,arm)
OPTEE_RUST_EXAMPLES_EXT_HOST_ARCH = $(if $(findstring aarch64,$(BR2_PACKAGE_OPTEE_RUST_EXAMPLES_EXT_CROSS_COMPILE_HOST)),aarch64,arm)

define OPTEE_RUST_EXAMPLES_EXT_BUILD_CMDS
	echo Building OP-TEE rust examples && \
	export RUSTUP_HOME=$(OPTEE_RUST_EXAMPLES_EXT_RUST_TC_PATH)/.rustup && \
	export CARGO_HOME=$(OPTEE_RUST_EXAMPLES_EXT_RUST_TC_PATH)/.cargo && \
	source $(OPTEE_RUST_EXAMPLES_EXT_RUST_TC_PATH)/.cargo/env && \
	export PATH="$(OPTEE_RUST_EXAMPLES_EXT_HOST_TC_BIN_PATH):$$PATH" && \
	export PATH="$(OPTEE_RUST_EXAMPLES_EXT_TA_TC_BIN_PATH):$$PATH" && \
	cd $(@D) && \
	TA_DEV_KIT_DIR=$(OPTEE_RUST_EXAMPLES_EXT_SDK) \
	OPTEE_CLIENT_EXPORT=$(TARGET_DIR) \
	./ci/build.sh \
		--ta $(OPTEE_RUST_EXAMPLES_EXT_TA_ARCH) \
		--host $(OPTEE_RUST_EXAMPLES_EXT_HOST_ARCH) \
		--ta-install-dir $(TARGET_DIR)/lib/optee_armtz \
		--ca-install-dir $(TARGET_DIR)/usr/bin \
		--plugin-install-dir $(TARGET_DIR)/usr/lib/tee-supplicant/plugins
endef

$(eval $(generic-package))
